src/Entity/RemoteBackup.php
<?php

namespace Herisson\Entity;

use Herisson\Repository\RemoteBackupRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RemoteBackupRepository::class)
 */
class RemoteBackup
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $size;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbBookmarks;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $friend_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSize(): ?int
    {
        return $this->size;
    }

    public function setSize(int $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getNbBookmarks(): ?int
    {
        return $this->nbBookmarks;
    }

    public function setNbBookmarks(int $nbBookmarks): self
    {
        $this->nbBookmarks = $nbBookmarks;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getFriendId(): ?int
    {
        return $this->friend_id;
    }

    public function setFriendId(int $friend_id): self
    {
        $this->friend_id = $friend_id;

        return $this;
    }
}

src/Form/RemoteBackupType.php
<?php

namespace Herisson\Form;

use Herisson\Entity\RemoteBackup;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RemoteBackupType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('size')
            ->add('nbBookmarks')
            ->add('created_at')
            ->add('friend_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => RemoteBackup::class,
        ]);
    }
}

src/Controller/RemoteBackupController.php
<?php

namespace Herisson\Controller;

use Herisson\Entity\RemoteBackup;
use Herisson\Form\RemoteBackupType;
use Herisson\Repository\RemoteBackupRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/remote/backup")
 */
class RemoteBackupController extends AbstractController
{
    /**
     * @Route("/", name="remote_backup_index", methods={"GET"})
     */
    public function index(RemoteBackupRepository $remoteBackupRepository): Response
    {
        return $this->render('remote_backup/index.html.twig', [
            'remote_backups' => $remoteBackupRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="remote_backup_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $remoteBackup = new RemoteBackup();
        $form = $this->createForm(RemoteBackupType::class, $remoteBackup);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($remoteBackup);
            $entityManager->flush();

            return $this->redirectToRoute('remote_backup_index');
        }

        return $this->render('remote_backup/new.html.twig', [
            'remote_backup' => $remoteBackup,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="remote_backup_show", methods={"GET"})
     */
    public function show(RemoteBackup $remoteBackup): Response
    {
        return $this->render('remote_backup/show.html.twig', [
            'remote_backup' => $remoteBackup,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="remote_backup_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, RemoteBackup $remoteBackup): Response
    {
        $form = $this->createForm(RemoteBackupType::class, $remoteBackup);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('remote_backup_index');
        }

        return $this->render('remote_backup/edit.html.twig', [
            'remote_backup' => $remoteBackup,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="remote_backup_delete", methods={"DELETE"})
     */
    public function delete(Request $request, RemoteBackup $remoteBackup): Response
    {
        if ($this->isCsrfTokenValid('delete'.$remoteBackup->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($remoteBackup);
            $entityManager->flush();
        }

        return $this->redirectToRoute('remote_backup_index');
    }
}

templates/remote_backup/_delete_form.html.twig
<form method="post" action="{{ path('remote_backup_delete', {'id': remote_backup.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ remote_backup.id) }}">
    <button class="btn">Delete</button>
</form>

templates/remote_backup/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/remote_backup/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit RemoteBackup{% endblock %}

{% block body %}
    <h1>Edit RemoteBackup</h1>

    {{ include('remote_backup/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('remote_backup_index') }}">back to list</a>

    {{ include('remote_backup/_delete_form.html.twig') }}
{% endblock %}

templates/remote_backup/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RemoteBackup index{% endblock %}

{% block body %}
    <h1>RemoteBackup index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Size</th>
                <th>NbBookmarks</th>
                <th>Created_at</th>
                <th>Friend_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for remote_backup in remote_backups %}
            <tr>
                <td>{{ remote_backup.id }}</td>
                <td>{{ remote_backup.size }}</td>
                <td>{{ remote_backup.nbBookmarks }}</td>
                <td>{{ remote_backup.createdAt ? remote_backup.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ remote_backup.friendId }}</td>
                <td>
                    <a href="{{ path('remote_backup_show', {'id': remote_backup.id}) }}">show</a>
                    <a href="{{ path('remote_backup_edit', {'id': remote_backup.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('remote_backup_new') }}">Create new</a>
{% endblock %}

templates/remote_backup/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New RemoteBackup{% endblock %}

{% block body %}
    <h1>Create new RemoteBackup</h1>

    {{ include('remote_backup/_form.html.twig') }}

    <a href="{{ path('remote_backup_index') }}">back to list</a>
{% endblock %}

templates/remote_backup/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RemoteBackup{% endblock %}

{% block body %}
    <h1>RemoteBackup</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ remote_backup.id }}</td>
            </tr>
            <tr>
                <th>Size</th>
                <td>{{ remote_backup.size }}</td>
            </tr>
            <tr>
                <th>NbBookmarks</th>
                <td>{{ remote_backup.nbBookmarks }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ remote_backup.createdAt ? remote_backup.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Friend_id</th>
                <td>{{ remote_backup.friendId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('remote_backup_index') }}">back to list</a>

    <a href="{{ path('remote_backup_edit', {'id': remote_backup.id}) }}">edit</a>

    {{ include('remote_backup/_delete_form.html.twig') }}
{% endblock %}